import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


class FrontendContractTests(unittest.TestCase):
    def test_idle_face_and_hidden_chat_contract_exist(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        self.assertIn('id="face-stage"', html)
        self.assertIn('id="idle-face"', html)
        self.assertIn('viewBox="140 84 1320 792"', html)
        self.assertEqual(html.count('class="eye-panel"'), 2)
        self.assertEqual(html.count('expression-brow '), 2)
        self.assertIn('class="mouth"', html)
        self.assertNotIn('class="connection-scan"', html)
        self.assertNotIn('class="mouth-opening"', html)
        self.assertNotIn('class="upper-lid"', html)
        self.assertNotIn('id="eye-fill"', html)
        self.assertNotIn('id="eye-fill-mirror"', html)
        self.assertIn('src="/static/idle-face.js?', html)
        self.assertNotIn('id="connect"', html)
        self.assertIn('id="disconnect"', html)
        self.assertIn('id="exit"', html)
        self.assertNotIn('id="expression-controls"', html)
        self.assertIn('id="settings-toggle"', html)
        self.assertIn('id="settings-panel"', html)
        self.assertIn('aria-label="Open settings"', html)
        self.assertIn('settingsPanel.classList.contains("open")', app)
        self.assertIn('id="connection-status"', html)
        self.assertIn('id="microphone-status"', html)
        self.assertIn('id="log"', html)
        self.assertNotIn("<img", html)
        self.assertNotIn("ada-visual.js", html)

    def test_idle_animation_is_visual_only_and_clamped(self) -> None:
        animation = (ROOT / "frontend/idle-face.js").read_text()
        styles = (ROOT / "frontend/style.css").read_text()
        self.assertIn("--gaze-x", animation)
        self.assertIn("--gaze-y", animation)
        self.assertIn("--blink", animation)
        self.assertIn("clamp(x, 18)", animation)
        self.assertIn("scheduleSaccade", animation)
        self.assertIn('"--blink-left"', animation)
        self.assertIn('"--blink-right"', animation)
        self.assertIn('"--brow-left-lift"', animation)
        self.assertIn('"--brow-right-lift"', animation)
        self.assertIn("blinkOnce(scheduleBlink, 1.3)", animation)
        self.assertIn("randomBetween(4500, 7000)", animation)
        self.assertIn(".mouth-track", styles)
        self.assertIn("var(--gaze-x) * .55", styles)
        self.assertIn(".eye-panel,.mouth", styles)
        self.assertIn("@keyframes mouth-aura", styles)
        self.assertIn("@keyframes face-breathing", styles)
        self.assertIn("@keyframes edge-shimmer", styles)
        self.assertNotIn("@keyframes connect-scan", styles)
        self.assertIn("setSpeechLevel", animation)
        self.assertIn("setConnecting", animation)
        self.assertIn("setExpression", animation)
        self.assertIn("expressionBrowPaths", animation)
        for expression in (
            "neutral", "sassy", "amused", "skeptical", "annoyed", "mad",
            "concerned", "surprised", "mischievous", "serious", "alert",
        ):
            self.assertIn(f'"{expression}"', animation)
            self.assertIn(f"#idle-face.expression-{expression}", styles)
        for color in (
            "#17dfff", "#ff3dbe", "#35ff9a", "#7d8cff", "#ff6b35",
            "#ff2400", "#4a8fff", "#ffd43b", "#b45cff", "#d9f7ff", "#ff8618",
        ):
            self.assertIn(f"--face-color: {color}", styles)
        self.assertIn("fill: var(--face-color)", styles)
        self.assertIn("stroke: var(--face-highlight)", styles)
        self.assertIn('round:', animation)
        self.assertIn('wide:', animation)
        self.assertIn('path.setAttribute("d"', animation)
        self.assertNotIn("getUserMedia", animation)
        self.assertNotIn("AudioContext", animation)

    def test_audio_pipeline_keeps_one_microphone_and_passive_output_meter(self) -> None:
        app = (ROOT / "frontend/app.js").read_text()
        self.assertEqual(app.count("getUserMedia("), 1)
        self.assertEqual(app.count("echoCancellation: false"), 1)
        self.assertEqual(app.count("autoGainControl: false"), 1)
        self.assertIn("PipeWire AEC", app)
        self.assertIn("playbackContext.createAnalyser()", app)
        self.assertIn("playbackNode.connect(playbackAnalyser)", app)
        self.assertIn("playbackAnalyser.connect(playbackContext.destination)", app)
        self.assertIn("getFloatTimeDomainData", app)
        self.assertIn("setSpeechLevel(smoothed)", app)
        self.assertIn("setSpeechLevel(0, true)", app)
        self.assertIn("this.startThreshold = 1440", app)
        self.assertIn("bufferedSamples", app)
        self.assertIn('type: "flush"', app)
        self.assertIn('fetch("/shutdown"', app)
        self.assertIn('case "expression"', app)
        self.assertNotIn("setAdaState", app)
        self.assertIn("window.idleFace?.setConnecting(true);\nconnect();", app)
        self.assertNotIn('\nconnectButton.addEventListener', app)

    def test_video_uses_native_pi_camera_without_touching_browser_audio(self) -> None:
        app = (ROOT / "frontend/app.js").read_text()
        provider = (ROOT / "backend/realtime_provider.py").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        camera = (ROOT / "backend/camera.py").read_text()
        start_script = (ROOT / "start.sh").read_text()
        self.assertNotIn("cameraStream", app)
        self.assertIn('shutil.which("rpicam-vid")', camera)
        self.assertIn('CameraHub(fps=5)', backend)
        self.assertIn('VisionBackendManager()', backend)
        self.assertIn('"--codec", "mjpeg"', camera)
        self.assertIn('"--rotation", "180"', camera)
        self.assertIn('async for frame in camera.frames()', backend)
        self.assertIn('local_speech_started', app)
        self.assertIn('local_speech_stopped', app)
        self.assertIn('control.get("type") == "local_speech_started"', backend)
        self.assertIn('clear_speech_activity_after_grace', backend)
        self.assertIn('VIDEO_MODE="${ADA_VIDEO_MODE:-activity}"', start_script)
        self.assertIn('start_home_assistant()', start_script)
        self.assertIn('compose -f "$HOME_ASSISTANT_COMPOSE_FILE" up -d', start_script)
        self.assertIn('HOME_ASSISTANT_TOKEN is missing or empty', start_script)
        self.assertIn('video=types.Blob(data=jpeg, mime_type="image/jpeg")', provider)
        self.assertIn("MEDIA_RESOLUTION_HIGH", provider)

    def test_pose_view_streams_shared_camera_and_draws_skeleton(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        self.assertIn('id="pose-toggle"', html)
        self.assertIn('id="pose-canvas"', html)
        self.assertIn('@app.websocket("/ws/pose")', backend)
        posture = (ROOT / "backend/posture.py").read_text()
        self.assertIn('PoseService(camera, pose_estimator, posture_monitor, posture_verifier, live_manager)', backend)
        self.assertIn('self.estimator.infer', posture)
        self.assertIn('POSE_CONNECTIONS', app)
        self.assertIn('createImageBitmap', app)

    def test_posture_tracker_ui_and_api_contract(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        self.assertIn('id="posture-settings"', html)
        self.assertIn('id="habit-reminder"', html)
        self.assertIn('id="posture-calibrate-slouch"', html)
        self.assertIn('id="posture-gemini"', html)
        self.assertIn('id="posture-habit"', html)
        self.assertIn('id="ada-system-prompt"', html)
        self.assertIn('id="habit-clear"', html)
        self.assertIn('id="habit-settings-toggle"', html)
        self.assertIn('id="habit-settings-panel"', html)
        self.assertIn('id="habit-settings-close"', html)
        self.assertGreater(html.index('id="posture-settings"'), html.index("</aside>"))
        self.assertIn("function openHabitSettings", app)
        self.assertIn("closeHabitSettings", app)
        self.assertIn('fetch("/api/habits/posture"', app)
        self.assertIn('/ws/habits', app)
        self.assertIn('@app.patch("/api/habits/posture/settings")', backend)
        self.assertIn('@app.post("/api/habits/posture/calibration/start"', backend)
        self.assertIn('@app.post("/api/habits/posture/calibration/start/{kind}"', backend)
        self.assertIn('GeminiPostureVerifier()', backend)
        self.assertIn('@app.post("/api/habits/reset")', backend)
        self.assertIn("posture_monitor.clear_habit_history()", backend)
        self.assertIn("Posture calibrations and settings will be kept", app)
        self.assertIn('@app.get("/api/settings/ada")', backend)
        self.assertIn('@app.patch("/api/settings/ada")', backend)
        self.assertNotIn('claim_boot_greeting', backend)
        self.assertNotIn('send_boot_greeting', backend)
        self.assertIn('window.confirm("Clear all habit events', app)

    def test_full_screen_habit_tracker_and_detection_signal(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        styles = (ROOT / "frontend/style.css").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        self.assertIn('id="habits-toggle"', html)
        self.assertIn('id="habits-panel"', html)
        self.assertIn('id="habits-list"', html)
        self.assertIn('id="habit-signal"', html)
        self.assertIn('id="office-lights-monitor"', html)
        self.assertIn('class="habit-bar"', app)
        self.assertIn("function habitProgress", app)
        self.assertIn("showHabitSignal", app)
        self.assertIn('HABIT_ACK_KEY', app)
        self.assertIn('LIGHTS LEFT ON WHILE AWAY', app)
        self.assertIn('["first_added", "status_changed"]', app)
        self.assertIn('@app.get("/api/habits")', backend)
        self.assertIn('@app.get("/api/habits/office-lights")', backend)
        self.assertIn('id="office-grace-minutes"', html)
        self.assertIn('id="office-poll-seconds"', html)
        self.assertIn('id="office-reset-hour"', html)
        self.assertIn('@app.patch("/api/habits/office-lights/settings")', backend)
        self.assertIn('notifier=notify_office_light_habit', backend)
        self.assertIn('await live_manager.send_text_turn(message)', backend)
        self.assertIn("habit_signal=habit_signal", backend)
        self.assertIn("@keyframes habit-signal-arrive", styles)
        self.assertIn("working_too_late", app)
        self.assertIn("not_drinking_enough_water", app)
        self.assertIn("junk_food", app)
        self.assertIn("response_window_seconds", app)
        self.assertIn("observation_window_seconds", app)
        self.assertIn("MANUAL_MONITORS", app)
        self.assertIn("monitor-run-now", app)
        self.assertIn("closeHabitSettings();", app)
        self.assertIn('/api/habits/monitors/${key}/trigger', app)
        self.assertIn('@app.post("/api/habits/monitors/{habit_key}/trigger"', backend)
        self.assertIn('id="water-check-countdown"', html)
        self.assertIn("function renderWaterCheck", app)
        self.assertIn("activeWaterChallenge.deadline", app)
        provider = (ROOT / "backend/realtime_provider.py").read_text()
        self.assertIn("report_habit_observation", provider)
        self.assertIn("get_habit_status", provider)
        self.assertIn("habit_state_getter=habit_tool_snapshot", backend)
        self.assertIn("def habit_tool_snapshot", backend)

    def test_home_assistant_device_page_and_local_controls(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        client = (ROOT / "backend/home_assistant.py").read_text()
        self.assertIn('id="home-toggle"', html)
        self.assertIn('id="home-panel"', html)
        self.assertIn('id="home-devices"', html)
        self.assertIn('fetchWithApiKey("/api/home-assistant/entities"', app)
        self.assertIn('@app.get("/api/home-assistant/entities")', backend)
        self.assertIn('@app.post("/api/home-assistant/entities/{entity_id}/power")', backend)
        self.assertIn('Device control is available only from this device', backend)
        self.assertIn('CONTROLLABLE_DOMAINS', client)

    def test_detect_view_streams_shared_camera_and_draws_coco_boxes(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        self.assertIn('id="detect-toggle"', html)
        self.assertIn('id="detect-canvas"', html)
        self.assertIn('@app.websocket("/ws/detect")', backend)
        self.assertIn('vision_backend.detection', backend)
        self.assertIn('@app.get("/api/vision/status")', backend)
        self.assertIn('vision_backend.status, True', backend)
        self.assertIn('key.startsWith("hailo_8_")', app)
        self.assertIn('drawDetectionFrame', app)
        self.assertIn('strokeRect', app)
        self.assertIn('/ws/detect', app)

    def test_no_frontend_image_assets_remain(self) -> None:
        assets = ROOT / "frontend/assets"
        self.assertFalse(assets.exists() and any(assets.rglob("*.*")))

    def test_pironman_drawer_uses_ada_backend_and_safe_controls(self) -> None:
        html = (ROOT / "frontend/index.html").read_text()
        app = (ROOT / "frontend/app.js").read_text()
        backend = (ROOT / "backend/main.py").read_text()
        self.assertIn('id="hardware-panel"', html)
        self.assertIn('fetch("/api/pironman"', app)
        self.assertIn('fetch("/api/pironman/controls"', app)
        self.assertIn('@app.get("/api/pironman")', backend)
        self.assertIn('@app.patch("/api/pironman/controls")', backend)
        self.assertIn('@app.post("/api/pironman/expression")', backend)
        self.assertNotIn('updateHardware("shutdown"', app)


if __name__ == "__main__":
    unittest.main()
